local C = require("andromeda.colors")
local M = {}

function M.get()
	return {
		Conceal = { bg = "NONE" },
		CurSearch = { fg = C.black0, bg = C.purple0, bold = true },
		Cursor = { fg = C.black0, bg = C.purple3, bold = true },
		lCursor = { fg = C.black0, bg = C.purple1, bold = true },
		CursorLine = { bg = C.black2 },
		DiffTextAdd = { bg = C.black4 },
		TermCursor = { fg = C.black0, bg = C.purple1 },
		ErrorMsg = { fg = C.red, bg = C.black0, bold = true },
		WinSeparator = { fg = C.black4, bg = C.black0 },
		Folded = { fg = C.cyan, bg = C.black4, italic = true },
		FoldColumn = { fg = C.black4 },
		SignColumn = { fg = C.white0 },
		ColorColumn = { bg = C.black2 },
		CursorColumn = { bg = C.black0 },
		IncSearch = { fg = C.black0, bg = C.purple2, bold = true },
		Substitute = { link = "IncSearch" },
		LineNr = { fg = C.black4 },
		CursorLineNr = { fg = C.white0, bold = true },
		MatchParen = { fg = C.black0, bg = C.orange },
		ModeMsg = { fg = C.cyan, bold = true },
		MoreMsg = { fg = C.purple2 },
		NonText = { fg = C.black3 },
		Normal = { fg = C.white0, bg = C.black0 },
		NormalFloat = { fg = C.white0, bg = C.black1 },
		FloatBorder = { fg = "NONE", bg = "NONE" },
		FloatTitle = { fg = C.cyan, bold = true },
		Pmenu = { bg = C.black1, fg = C.white0 },
		PmenuSel = { bg = C.purple3, fg = C.black0, bold = true },
		PmenuSbar = { bg = C.black3 },
		PmenuThumb = { bg = C.purple0 },
		PmenuExtra = { fg = C.black3 },
		PmenuExtraSel = { fg = C.black3 },
		Question = { fg = C.cyan, bold = true },
		QuickFixLine = { bg = C.black3, bold = true },
		Search = { bg = C.yellow, fg = C.black0, bold = true },
		SpecialKey = { link = "NonText" },
		SpellBad = { sp = C.red, undercurl = true },
		SpellCap = { sp = C.yellow, undercurl = true },
		SpellLocal = { sp = C.cyan, undercurl = true },
		SpellRare = { sp = C.green, undercurl = true },
		StatusLine = { fg = C.white1, bg = C.black2, bold = true },
		TabLine = { bg = C.black1, fg = C.black4 },
		TabLineFill = { bg = C.black0 },
		TabLineSel = { fg = C.yellow, bg = C.black2, bold = true },
		Title = { fg = C.cyan, bold = true },
		Visual = { bg = C.black3, bold = true },
		VisualNOS = { bg = C.black3, bold = true },
		WarningMsg = { fg = C.orange, bold = true },
		Whitespace = { fg = C.black3 },
		WildMenu = { bg = C.black3, fg = C.white0 },
		WinBar = { fg = C.pink, bg = C.black1, bold = true },
		VertSplit = { fg = C.black3 },

		-- Non current window highlights
		NormalNC = { fg = C.white1, bg = C.black1 },
		WinBarNC = { link = "WinBar" },
		StatusLineNC = { fg = C.white1, bg = C.black3 },
		TermCursorNC = { fg = C.white1, bg = C.black4 },
	}
end

return M
