local C = require("andromeda.colors")
local M = {}

function M.get()
	return {
		Comment = { fg = C.white1, italic = true },
		SpecialComment = { link = "Special" },
		Constant = { fg = C.yellow },
		String = { fg = C.green },
		Character = { fg = C.cyan },
		Number = { fg = C.orange },
		Float = { link = "Number" },
		Boolean = { fg = C.orange },
		Function = { fg = C.purple1, bold = true },
		Identifier = { fg = C.purple3 },
		Statement = { fg = C.purple0, bold = true },
		Conditional = { fg = C.purple2, bold = true },
		Repeat = { link = "Conditional" },
		Label = { fg = C.cyan },
		Operator = { fg = C.purple2 },
		Keyword = { fg = C.purple0, bold = true },
		Exception = { fg = C.purple0 },
		PreProc = { fg = C.darkcyan },
		Include = { fg = C.purple1 },
		Define = { link = "PreProc" },
		Macro = { fg = C.purple0 },
		PreCondit = { link = "PreProc" },
		StorageClass = { fg = C.yellow },
		Structure = { fg = C.yellow },
		Special = { fg = C.pink },
		Type = { fg = C.cyan, bold = true },
		Typedef = { link = "Type" },
		SpecialChar = { link = "Special" },
		Tag = { fg = C.purple2, bold = true },
		Delimiter = { fg = C.white1 },
		Debug = { link = "Special" },
		Error = { fg = C.red, bold = true },
		Todo = { bg = C.yellow, fg = C.black3, bold = true },
		qfLineNr = { fg = C.yellow },
		qfFileName = { fg = C.cyan },
		htmlH1 = { fg = C.pink, bold = true },
		htmlH2 = { fg = C.cyan, bold = true },
		mkdCodeDelimiter = { bg = C.white0, fg = C.white0 },
		mkdCodeStart = { fg = C.orange, bold = true },
		mkdCodeEnd = { fg = C.orange, bold = true },
		debugPC = { bg = C.black1 },
		debugBreakpoint = { bg = C.white0, fg = C.black4 },
		illuminatedWord = { bg = C.white1 },
		illuminatedCurWord = { bg = C.white1 },
		diffAdded = { fg = C.green },
		diffRemoved = { fg = C.red },
		diffChanged = { fg = C.cyan },
		diffOldFile = { fg = C.yellow },
		diffNewFile = { fg = C.orange },
		diffFile = { fg = C.cyan },
		diffLine = { fg = C.black4 },
		diffIndexLine = { fg = C.darkcyan },
		DiffAdd = { bg = C.darkgreen },
		DiffChange = { bg = C.darkcyan },
		DiffDelete = { bg = C.darkred },
		DiffText = { bg = C.darkcyan },

		-- NeoVim
		healthError = { fg = C.red },
		healthSuccess = { fg = C.darkcyan },
		healthWarning = { fg = C.yellow },

		-- glyphs
		GlyphPalette1 = { fg = C.red },
		GlyphPalette2 = { fg = C.darkcyan },
		GlyphPalette3 = { fg = C.yellow },
		GlyphPalette4 = { fg = C.cyan },
		GlyphPalette6 = { fg = C.darkcyan },
		GlyphPalette7 = { fg = C.white0 },
		GlyphPalette9 = { fg = C.red },

		-- rainbow
		rainbow1 = { fg = C.red },
		rainbow2 = { fg = C.orange },
		rainbow3 = { fg = C.yellow },
		rainbow4 = { fg = C.green },
		rainbow5 = { fg = C.cyan },
		rainbow6 = { fg = C.purple0 },

		-- csv
		csvCol0 = { fg = C.red },
		csvCol1 = { fg = C.orange },
		csvCol2 = { fg = C.yellow },
		csvCol3 = { fg = C.green },
		csvCol4 = { fg = C.cyan },
		csvCol5 = { fg = C.darkcyan },
		csvCol6 = { fg = C.purple0 },
		csvCol7 = { fg = C.purple1 },
		csvCol8 = { fg = C.purple2 },
	}
end

return M
